# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nahual',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='nahual',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nahual',
            name='foto',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='iconos_nahual'),
        ),
        migrations.AddField(
            model_name='nahual',
            name='simbolos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
