# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_auto_20170426_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='nahual',
            name='aplicacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nahual',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nahual',
            name='codigo',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='nahual',
            name='interpretacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
