# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_auto_20170427_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='nahual',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
