# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_nahual_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nahual',
            name='aplicacion',
        ),
        migrations.RemoveField(
            model_name='nahual',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='nahual',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='nahual',
            name='simbolos',
        ),
        migrations.AlterField(
            model_name='nahual',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
